packages:
  - .
  - apps/*
catalogs:
  # Can be referenced through "catalog:trpc"
  trpc:
    '@trpc/client': ^11.0.1
    '@trpc/server': ^11.0.1
  # Can be referenced through "catalog:repo"
  repo:
    nuxt: 3.16.1
    superjson: ^2.2.2
    zod: ^3.24.2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
