packages:
  - .
  - apps/*
catalogs:
  repo:
    nuxt: 3.16.1
    superjson: ^2.2.2
    zod: ^3.24.2
  trpc:
    '@trpc/client': ^11.0.2
    '@trpc/server': ^11.0.2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - rolldown
  - sharp
