packages:
  - .
  - apps/*
catalog:
  '@trpc/client': ^11.0.0
  '@trpc/server': ^11.0.0
  nuxt: 3.16.1
  superjson: ^2.2.2
  zod: ^3.24.2
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
